"""admin/user roles and test visibility

Revision ID: 0002_roles_and_test_visibility
Revises: 0001_initial_schema
Create Date: 2026-10-06

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_roles_and_test_visibility"
down_revision: Union[str, None] = "0001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("users", sa.Column("role", sa.String(20), nullable=False, server_default="user"))
    op.add_column("tests", sa.Column("visibility", sa.String(20), nullable=False, server_default="draft"))
    # Pre-existing tests were generated by their owner for themselves.
    op.execute("UPDATE tests SET visibility = 'private'")


def downgrade() -> None:
    op.drop_column("tests", "visibility")
    op.drop_column("users", "role")
